### ISSUE TITLE
邀请你加入FCC中文社区翻译协作群

### ISSUE THREAD

**Issue by workcheng** [liangyulai/coding#1]
![FCC中文社区翻译协作群](https://cloud.githubusercontent.com/assets/9999969/15797315/fb476a64-2a45-11e6-835e-33aeabbf597c.png)

**Comment by liangyulai** [comment]
@workcheng  抱歉，一直没有注意到这个邀请，能给我再发一下二维码吗？这个已经过期了，谢谢。
